### ISSUE TITLE
Not accommodating baseurl

### ISSUE THREAD

**Issue by mjohnq3** [octopress/image-tag#1]
This doesn't appear to accommodate baseurl for a site hosted on a GitHub Project page. I've tried adding:

```
{% img {{ site.baseurl }}/images/image.jpg "Image" title:"Image" %}
```

or

```
{% img /images/image.jpg | prepend: site.baseurl "Image" title:"Image" %}
```

but the resulting markup is always:

```
<p><img src="/images/image.jpg" alt="Image" title="Image"></p>
```

Is there some way of incorporating baseurl?

**Comment by imathis** [comment]
I've just released 1.1.0 where this should be fixed. It's a great idea to be able to pass liquid variables with the tag, but just so you know the Jekyll docs specify that `baseurl` is to be used for serving sites from a subdirectory. It is not meant to be used to generate urls in templates. You might want to use a different variable name for that purpose. Perhaps something like `subdir`.

Anyway Cheers, and thanks for helping me make this better!

**Comment by mjohnq3** [comment]
Thanks. But this seems to be confusing to everyone (or perhaps just me) including the people who documented it: http://jekyllrb.com/docs/github-pages/#project-page-url-structure

It implies that you reference all 'assets' using baseurl. Unless I'm reading it wrong.

**Comment by imathis** [comment]
Ah ok. I hadn't seen this updated documentation. For a long time, this has gone back and forth. Seems like you're doing it right now though. Thanks for educating me :+1:

**Comment by mjohnq3** [comment]
Yes, I have seen comments that it's gone back and forth. It was just as much about educating myself as anyone else. Thanks for your quick response.

**Comment by imathis** [comment]
I was thinking about this some more and I remembered, the confusion around this was when people tried to use it anywhere _other_ than GitHub project pages. Anyway, cheers.

**Comment by parkr** [comment]
@mjohnq3 I tried to elucidate here: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/

**Comment by imathis** [comment]
@parkr Ah yes I had forgotten about that post. I probably need to see about supporting `baseurl` better in the Octopress Ink based theme stuff I'm working on. Thanks for the reminder!

**Comment by mjohnq3** [comment]
@parker Yes, I have read that... more than a few times!
