### ISSUE TITLE
Liquid Exception: Unknown tag 'img'

### ISSUE THREAD

**Issue by e9t** [octopress/image-tag#2]
I'm getting the error `Liquid Exception: Unknown tag 'img'` when generating posts containing `img` tags.
Has anyone had and solved this issue?
I've also left details at https://github.com/octopress/octopress/issues/70#issuecomment-124945378.

**Comment by e9t** [comment]
See http://jekyllrb.com/docs/plugins/#installing-a-plugin for those who have problems in the future.

**Comment by timcosgrove** [comment]
@e9t Reading this and also this comment: https://github.com/octopress/octopress/issues/70#issuecomment-125000805

does this mean that the Jekyll documentation is inaccurate? i.e. Option 3 (install plugins via Bundler) does not say anything about specifying _config.yml, but it appears that you need _config.yml when install the plugin via Bundler as well as when installing via the `gem` command.

Thanks!
